BEGIN;

CREATE TABLE IF NOT EXISTS Tags (
    "TagID" NVARCHAR(36) PRIMARY KEY NOT NULL,
    "UserID" NVARCHAR(36) NOT NULL,
    "Label" NVARCHAR(64) NOT NULL,
    FOREIGN KEY ("UserID") REFERENCES Users ("UserID")
);

CREATE TABLE IF NOT EXISTS Tags_Credentials (
    "TagID" NVARCHAR(36) NOT NULL,
    "CredentialID" NVARCHAR(36) NOT NULL,
    PRIMARY KEY ("TagID", "CredentialID"),
    FOREIGN KEY ("TagID") REFERENCES Tags ("TagID"),
    FOREIGN KEY ("CredentialID") REFERENCES Credentials ("CredentialID")
);

COMMIT;
