name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_PROJECT_FOLDER: ${{ github.workspace }}/Vault
    defaults:
      run:
        working-directory: ${{ env.DOTNET_PROJECT_FOLDER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Restore NuGet dependencies
        run: dotnet restore

      - name: Restore NPM dependencies
        run: npm ci

      - name: Build/test UI
        run: ./build-front-end.sh

      - name: Build application
        run: dotnet build
