name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_PROJECT_FOLDER: ${{ github.workspace }}/Vault
    defaults:
      run:
        working-directory: ${{ env.DOTNET_PROJECT_FOLDER }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Restore NuGet dependencies
        run: dotnet restore

      - name: Restore NPM dependencies
        run: npm ci

      - name: Build UI
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Build application
        run: dotnet build
